# Generated by Django 5.0.6 on 2024-05-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='days',
            field=models.CharField(choices=[('sun-tue-thu', 'sunday-tuesday-thursday'), ('mon-wed', 'monday-wednesday'), ('sun-thu', 'sunday-thursday')], max_length=20),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='end_time',
            field=models.TimeField(choices=[('9:15', '9:15'), ('10:45', '10:45'), ('12:15', '12:15'), ('1:45', '1:45'), ('3:15', '3:15')]),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='start_time',
            field=models.TimeField(choices=[('8:00', '8:00'), ('9:30', '9:30'), ('11:00', '11:00'), ('12:30', '12:30'), ('2:00', '2:00')]),
        ),
    ]
